/* The Recursive Tarot — quick-jump search engine (no AI, no server).
 *
 * Reads search-index.json (generated by scripts/build_search_index.py — never hand-edit it)
 * and ranks cards, decks, "across every deck" rows, people, books, courses, chapter
 * sections and site pages for a typed query. The search box in site-header.js uses it;
 * any other tool can too (see docs/QUICK-JUMP-SEARCH.md):
 *
 *   browser:  RTQuickJump.load(rootPrefix).then(idx => RTQuickJump.search(idx, 'justice golden dawn'))
 *   node:     const qj = require('./quick-jump.js');
 *             const idx = qj.prepare(require('./search-index.json'), '');
 *             qj.search(idx, 'justice golden dawn')
 *
 * Ranking, in one paragraph: each query word scores by WHERE it matches — the item's own
 * name (10), its aliases (9: the trump's name in every tradition, its numeral, suit and
 * rank words), its deck or course (5), or a weaker relation (3: keywords, a card a chapter
 * mentions). Matching every word adds 15. A row whose only match is its deck is dropped
 * unless it matched every word, so "justice golden dawn" gives the Golden Dawn Justice,
 * then Justice across every deck, then Justice in each deck, then the chapters.
 */
(function (root) {
  'use strict';

  var STOP = {};
  ('the of a an and la le les il lo de du des di del della in on to for with its is')
    .split(' ').forEach(function (w) { STOP[w] = 1; });

  var KIND_ORDER = { c: 0, x: 1, d: 2, p: 3, b: 3, g: 4, o: 5, h: 6 };
  var ROMAN = /^(x{0,3})(ix|iv|v?i{0,3})$/;

  function norm(s) {
    return String(s == null ? '' : s).normalize('NFD').replace(/[̀-ͯ]/g, '')
      .toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  }
  function split(s) { var n = norm(s); return n ? n.split(' ') : []; }

  // Short tokens, numbers and roman numerals must match a whole word ("xi" is not "xii");
  // everything else matches a word's start, so results appear while typing.
  function exactToken(t) { return t.length <= 2 || /^\d+$/.test(t) || ROMAN.test(t); }
  function hit(tok, exact, arr) {
    for (var i = 0; i < arr.length; i++) {
      if (exact ? arr[i] === tok : arr[i].lastIndexOf(tok, 0) === 0) return true;
    }
    return false;
  }

  function prepare(data, prefix) {
    prefix = prefix || '';
    var decks = data.decks || [], courses = data.courses || [], imgBase = data.img || '';
    var deckWords = decks.map(function (d) { return split(d.w || d.n); });
    var courseWords = courses.map(function (c) { return split(c.t); });
    var cardsUrl = prefix + 'viewers/cards.html?src=../tarot/';
    var courseUrl = prefix + 'pages/course-viewer.html?course=';
    var rows = (data.entries || []).map(function (e, n) {
      var deck = e.d != null ? decks[e.d] : null;
      var course = e.c != null ? courses[e.c] : null;
      var href, sub;
      switch (e.k) {
        case 'c': case 'p': case 'b':
          href = cardsUrl + deck.s + '/grammar.json&item=' + encodeURIComponent(e.i);
          sub = e.k === 'c' ? deck.n : (e.k === 'p' ? 'Person' : 'Book') + ' · the sources';
          break;
        case 'd':
          href = cardsUrl + deck.s + '/grammar.json';
          sub = 'Deck · ' + e.n + ' cards';
          break;
        case 'x':
          href = prefix + 'viewers/prototypes/lenses.html?card=' + encodeURIComponent(e.i);
          sub = 'Every deck, side by side · ' + e.n + ' decks';
          break;
        case 'o':
          href = courseUrl + course.id;
          sub = 'Course';
          break;
        case 'h':
          href = courseUrl + course.id + '#' + encodeURIComponent(e.h);
          sub = course.t;
          break;
        default:
          href = prefix + e.u;
          sub = 'Page';
      }
      var img = e.img ? (e.img.charAt(0) === '~' ? imgBase + e.img.slice(1) : e.img) : null;
      return {
        kind: e.k, title: e.t, sub: sub, href: href, img: img, n: n,
        T: split(e.t),
        A: e.k === 'd' ? deckWords[e.d] : split(e.a),        // a deck's own names are its aliases
        D: e.k === 'd' ? [] : deck ? deckWords[e.d] : (e.k === 'h' ? courseWords[e.c] : []),
        X: split(e.x)
      };
    });
    var allDeckWords = [].concat.apply([], deckWords);
    return { rows: rows, data: data, deckWords: allDeckWords };
  }

  function search(index, query, limit) {
    limit = limit || 60;
    var toks = split(query).filter(function (t) { return !STOP[t]; });
    if (!toks.length) return [];
    var ex = toks.map(exactToken), out = [];
    // Words that name a deck ("golden", "dawn", "rws") narrow; the other words say WHICH
    // card. A card whose own name or aliases carry every one of those other words comes
    // first (tier 1), whatever deck it is in; the deck words then order the tier.
    var cardToks = [];
    for (var k = 0; k < toks.length; k++) if (!hit(toks[k], ex[k], index.deckWords)) cardToks.push(k);
    for (var r = 0; r < index.rows.length; r++) {
      var row = index.rows[r], score = 0, all = true, named = false, own = {};
      for (var i = 0; i < toks.length; i++) {
        var t = toks[i], e = ex[i], best = 0;
        if (hit(t, e, row.T)) { best = 10; named = true; own[i] = 1; }
        else if (hit(t, e, row.A)) { best = 9; named = true; own[i] = 1; }
        else if (hit(t, e, row.D)) { best = 5; }
        else if (hit(t, e, row.X)) { best = 3; named = true; }
        if (!best) all = false;
        score += best;
      }
      if (!score || (!named && !all)) continue;
      if (all) score += 15;
      if (row.kind === 'x' || (row.kind === 'd' && named)) score += 1;
      if (row.kind === 'o' || row.kind === 'h') score = all ? score - 0.5 : score * 0.55;
      if (cardToks.length && (row.kind === 'c' || row.kind === 'x') &&
          cardToks.every(function (k) { return own[k]; })) score += 100;
      out.push({ row: row, score: score });
    }
    out.sort(function (a, b) {
      return b.score - a.score || KIND_ORDER[a.row.kind] - KIND_ORDER[b.row.kind] || a.row.n - b.row.n;
    });
    return out.slice(0, limit).map(function (o) {
      var w = o.row;
      return { kind: w.kind, title: w.title, sub: w.sub, href: w.href, img: w.img, score: o.score };
    });
  }

  var cache = {};
  function load(prefix) {
    prefix = prefix || '';
    if (!cache[prefix]) {
      cache[prefix] = fetch(prefix + 'search-index.json')
        .then(function (r) { if (!r.ok) throw new Error('search index HTTP ' + r.status); return r.json(); })
        .then(function (d) { return prepare(d, prefix); });
      cache[prefix].catch(function () { delete cache[prefix]; });
    }
    return cache[prefix];
  }

  var API = { load: load, prepare: prepare, search: search, norm: norm };
  if (typeof module !== 'undefined' && module.exports) module.exports = API;
  else root.RTQuickJump = API;
})(typeof window !== 'undefined' ? window : this);
