/* Shared site header for the Recursive Tarot static site.
 * One definition, used by every page (root + viewers/ + pages/). Style-isolated
 * via Shadow DOM so each viewer's own CSS can't override it. Path-aware so links
 * resolve from both the repo root and the /viewers/ subdir.
 *
 * Usage:  <script src="<path-to>/site-header.js?v=7"></script>
 *         <site-header active="cards"></site-header>
 * The `active` attribute highlights the matching tab; if omitted it is
 * auto-detected from the filename.
 *
 * Nav model (June 2026): two groups, all right-aligned.
 *  - VIEWS  — previews of the same data (Cards, Explorer, Tree of Tarot, Timeline,
 *             Tree, Genealogy), introduced by a tiny "views" caption.
 *  - TOOLS  — different-natured pages, each colour-coded: Caster (violet),
 *             Course (green), Shop (gold), GitHub (muted, external).
 */
(function () {
  if (customElements.get('site-header')) return;

  // Path back to the repo root — depth-aware so it works at any nesting
  // (root, /viewers/, /pages/, AND /viewers/prototypes/, /pages/book/ …).
  const _segs = location.pathname.split('/').filter(Boolean);
  const PFX = '../'.repeat(Math.max(0, _segs.length - 1));

  // Figure-capture mode (?fig=1): hide a viewer's own control toolbars so headless
  // screenshots become clean static plates for the print book. Only when explicitly asked.
  if (new URLSearchParams(location.search).get('fig') === '1') {
    const s = document.createElement('style');
    s.textContent = '.hint,.controls,.toolbar{display:none!important}';
    (document.head || document.documentElement).appendChild(s);
  }

  // Shared-identity widget (reads the .recursive.eco session cookie; L1 of the
  // integration ladder). Loaded once; renders as <recursive-auth> in the bar.
  if (!document.querySelector('script[data-recursive-auth]')) {
    const s = document.createElement('script');
    s.src = PFX + 'auth-widget.js?v=2';
    s.dataset.recursiveAuth = '1';
    document.head.appendChild(s);
  }

  // [key, label, href] — split by level
  const CARD_VIEWS = [
    ['explorer', 'Explorer', PFX + 'viewers/explorer.html'],
    ['cards',    'Cards',    PFX + 'viewers/cards.html'],
    ['lenses',   'Lenses', PFX + 'viewers/prototypes/lenses.html'],
    ['tree',     'Tree',     PFX + 'viewers/tree-viewer.html'],
    ['table',    'Card Table', PFX + 'viewers/table.html'],
  ];
  const GRAMMAR_VIEWS = [
    ['treeoflife', 'Tree of Tarot', PFX + 'viewers/genealogy-tree.html'],
    ['timeline',   'Timeline',     PFX + 'viewers/timeline.html'],
    ['genealogy',  'Genealogy',    PFX + 'genealogy.html'],
    ['channels',   'Channels',     PFX + 'pages/channels.html'],
  ];
  // [key, label, href, cssClass, external?]
  const TOOLS = [
    ['contribute', 'Contribute', PFX + 'pages/contribute.html', 't-contribute'],
    ['shop',   'Shop',    PFX + 'pages/shop.html',          't-shop'],
    ['github', 'GitHub ↗',  'https://github.com/PlayfulProcess/recursive-tarot', 't-github', true],
  ];
  // Play — a dropdown of the games + readings (the pill itself links to the Play hub).
  const PLAY_MENU = [
    [PFX + 'pages/games/tarocchino.html', 'Tarocchino di Bologna'],
    [PFX + 'pages/games/madiao.html',     'Ma Diao 馬吊'],
    [PFX + 'pages/games/trionfi.html',    'Trionfi'],
    [PFX + 'viewers/caster-studio.html',  'Spread Caster — build · cast · send'],
    [PFX + 'viewers/table.html',          'Card Table — less · keep · more'],
    [PFX + 'viewers/cards.html?src=../tarot/bus-passengers/grammar.json', 'Bus Passengers — who’s driving?'],
    ['https://flow.recursive.eco/',   'Oracle ↗', true],
    [PFX + 'pages/play.html',             'All games & readings →'],
  ];
  // Home — a dropdown that uncollapses to About (the pill itself links to the homepage).
  const HOME_MENU = [
    [PFX + 'index.html',        'Home'],
    [PFX + 'pages/about.html',  'About'],
  ];
  // Courses — grouped into three topics; each is a course-viewer ?course=… (deep-linkable with #section).
  const COURSE_GROUPS = [
    ['Start here', [
      ['history-of-tarot',                'The History of Tarot'],
      ['how-tarot-works',                 'How the Cards Can Work'],
      ['how-to-contribute',               'Ways to Contribute'],
    ]],
    ['More', [
      ['reading-the-cards',               'Reading the Cards'],
      ['tarot-today',                     'Tarot Today'],
      ['why-a-reading-feels-personal',    'Why a Reading Feels So Personal'],
      ['what-a-reading-can-do',           'What a Reading Can Do'],
      ['your-card-table',                 'Your Card Table'],
      ['walking-the-golden-dawn-path',     'The Golden Dawn — the Map and the Walk'],
      ['working-with-claude-desktop',     'Working with Claude Desktop'],
    ]],
  ];

  // Quick-jump search (Oct 2026): the box in the bar, its results, and the phone sheet.
  // The engine (ranking) is quick-jump.js; the data is search-index.json, generated by
  // scripts/build_search_index.py. Both load on first use, never with the page.
  const QJ_SVG = (inner, size) => `<svg viewBox="0 0 24 24" width="${size || 18}" height="${size || 18}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${inner}</svg>`;
  const QJ_ICON = {
    search: '<circle cx="11" cy="11" r="6.5"/><path d="M16 16l4.5 4.5"/>',
    close:  '<path d="M6 6l12 12M18 6L6 18"/>',
    c:      '<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M9.5 8h5M9.5 16h5"/>',
    d:      '<rect x="3" y="6" width="11" height="15" rx="1.5"/><path d="M8 6l3-1.5L20 9v11"/>',
    x:      '<path d="M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM13 13h7v7h-7z"/>',
    p:      '<circle cx="12" cy="8" r="3.5"/><path d="M5 20a7 7 0 0 1 14 0"/>',
    b:      '<path d="M5 4h11a2 2 0 0 1 2 2v14H7a2 2 0 0 0-2 2z"/><path d="M5 4v16"/>',
    o:      '<path d="M2 6c3-1.5 7-1.5 10 1 3-2.5 7-2.5 10-1v13c-3-1.5-7-1.5-10 1-3-2.5-7-2.5-10-1z"/><path d="M12 7v13"/>',
    h:      '<path d="M5 4h14M5 9h14M5 14h9M5 19h6"/>',
    g:      '<path d="M9 15l6-6"/><path d="M11 6l1-1a4 4 0 0 1 6 6l-1 1"/><path d="M13 18l-1 1a4 4 0 0 1-6-6l1-1"/>',
  };
  const QJ_TRY = ['Justice', 'Golden Dawn', 'Queen of Cups', 'XI', 'Pathworking', 'Marseille'];
  const qjEsc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

  function autoActive() {
    const f = location.pathname.split('/').pop() || 'index.html';
    if (f.startsWith('cards')) return 'cards';
    if (f.startsWith('explorer')) return 'explorer';
    if (f.startsWith('lenses')) return 'lenses';
    if (f.startsWith('genealogy-tree')) return 'treeoflife';
    if (f.startsWith('timeline')) return 'timeline';
    if (f.startsWith('tree-viewer')) return 'tree';
    if (f.startsWith('play') || f.startsWith('caster') || f.startsWith('table') || f.startsWith('trionfi') || location.pathname.includes('/games/')) return 'play';
    if (f.startsWith('genealogy')) return 'genealogy';
    if (f.startsWith('channels')) return 'channels';
    if (f.startsWith('course')) return 'course';
    if (f.startsWith('shop')) return 'shop';
    if (f.startsWith('contribute')) return 'contribute';
    return 'home';
  }

  class SiteHeader extends HTMLElement {
    connectedCallback() {
      // Embedded (iframed into a course/book): render no header at all.
      if (new URLSearchParams(location.search).get('embed') === '1') { this.style.display = 'none'; return; }
      // Museum/Editorial webfonts — injected once into the document head so every page
      // (light DOM and this shadow DOM) renders in Cormorant / Fraunces / Inter.
      if (!document.getElementById('rt-fonts')) {
        const fl = document.createElement('link'); fl.id = 'rt-fonts'; fl.rel = 'stylesheet';
        fl.href = 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400&family=Inter:wght@400;500;600&display=swap';
        document.head.appendChild(fl);
      }
      // The shared SVG icon library — one source, available as <rt-icon name="…"> on every page.
      if (!document.getElementById('rt-icons-lib')) {
        const si = document.createElement('script'); si.id = 'rt-icons-lib'; si.src = PFX + 'icons.js';
        document.head.appendChild(si);
      }
      const active = this.getAttribute('active') || autoActive();
      const root = this.attachShadow({ mode: 'open' });
      const tab = ([key, label, href, cls, ext]) =>
        `<a class="tab ${cls || ''}${key === active ? ' active' : ''}" href="${href}"${ext ? ' target="_blank" rel="noopener"' : ''}>${label}</a>`;
      // Dropdown menu item (used inside the Views menu) — highlights the current page.
      const menuItem = ([key, label, href, cls, ext]) =>
        `<a class="${key === active ? 'on' : ''}" href="${href}"${ext ? ' target="_blank" rel="noopener"' : ''}>${label}</a>`;
      const VIEW_KEYS = ['explorer', 'cards', 'lenses', 'tree', 'treeoflife', 'timeline', 'genealogy', 'channels'];
      const viewActive = VIEW_KEYS.includes(active);
      root.innerHTML = `
        <style>
          :host{ display:block; position:sticky; top:0; z-index:50;
                 background:#fbf9f3; padding:0; margin:0; border:0; font-size:14px;
                 transition:transform .25s ease; }
          @media (prefers-reduced-motion: reduce){ :host{ transition:none; } .tab, .dd-menu a, .brand{ transition:none !important; } }
          .bar{
            display:flex; align-items:center; gap:14px; flex-wrap:wrap;
            padding:13px 20px; background:#fbf9f3;
            border-bottom:1px solid #d8d2c6;
            font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;
          }
          .brand{ display:flex; flex-direction:row; align-items:center; gap:10px; margin-right:4px; }
          .brand-logo, .brand-name{ display:inline-flex; align-items:center; text-decoration:none; }
          .brand-logo{ border-radius:50%; }
          .brand-name .name{ font-family:"Fraunces",Georgia,serif; font-size:21px; font-weight:600; letter-spacing:.4px; color:#221f1a; white-space:nowrap; }
          .brand-name:hover .name{ color:#000; }
          .brand-name .name .gold{ color:#9a7322; }
          .brand svg{ flex-shrink:0; }
          .spacer{ flex:1 1 auto; }
          nav{ display:flex; gap:4px; flex-wrap:wrap; align-items:center; }
          .cap{ font-size:9.5px; text-transform:uppercase; letter-spacing:.16em;
                color:#8a8273; margin:0 2px 0 6px; user-select:none; }
          .cap.card-cap{ color:#9a7322; }
          .cap.gram-cap{ color:#6b6457; }
          .sep{ width:1px; height:20px; background:#d8d2c6; margin:0 6px; }
          /* one restrained editorial language for every nav item — text links,
             gold on hover, a hairline underline when active. No pills, no per-tool colour. */
          .tab{
            color:#6b6457; text-decoration:none; font-size:13px; font-weight:500;
            padding:7px 9px; white-space:nowrap; transition:color .15s;
            border:0; border-bottom:1.5px solid transparent; border-radius:0;
          }
          .tab:hover{ color:#9a7322; }
          .tab.active{ color:#9a7322; font-weight:600; border-bottom-color:#9a7322; }
          .t-caster,.t-course,.t-shop,.t-github,.t-contribute{ color:#6b6457; border:0; border-bottom:1.5px solid transparent; border-radius:0; }
          .t-caster:hover,.t-course:hover,.t-shop:hover,.t-github:hover,.t-contribute:hover{ color:#9a7322; background:transparent; }
          /* dropdowns */
          .dd{ position:relative; }
          .dd-btn{ background:none; font-family:inherit; cursor:pointer; }
          .dd-btn::after{ content:""; display:inline-block; width:5px; height:5px; margin-left:7px;
            border-right:1.4px solid currentColor; border-bottom:1.4px solid currentColor;
            transform:rotate(45deg) translateY(-2px); opacity:.5; }
          .dd-menu{ position:absolute; top:calc(100% + 8px); right:0; min-width:220px;
            max-width:min(300px,calc(100vw - 16px)); background:#ffffff; border:1px solid #d8d2c6;
            border-radius:8px; padding:7px; box-shadow:0 16px 44px -18px rgba(60,45,20,.45); display:none; z-index:60;
            overflow-y:auto; }
          /* Horizontal/vertical clamping is computed in JS (positionMenu, below), not a fixed
             breakpoint: a left-side trigger (Home, Views) overflows the left edge whenever the
             panel is wider than the space to its left, which happens at tablet widths (~760–950px)
             just as much as on phones — a single max-width media query missed that range entirely. */
          /* Open state is .open (JS-managed, incl. desktop hover) or keyboard focus — never
             raw :hover: the gap under the trigger made :hover a dead zone (the old ::before
             bridge couldn't cover it — overflow-y:auto clips pseudo-content above the panel). */
          .dd:focus-within .dd-menu, .dd.open .dd-menu{ display:block; }
          .dd.open .dd-btn::after{ transform:rotate(225deg) translateY(2px); opacity:.85; }
          .dd-menu a{ display:block; color:#4a4439; text-decoration:none; font-size:13px;
            padding:8px 10px; border-radius:7px; white-space:nowrap; }
          .dd-menu a:hover{ background:#f1ece1; color:#221f1a; }
          .dd-menu a[href*="recursive.eco"]{ color:#9333ea; }
          .dd-menu a.on{ color:#221f1a; background:#f1ece1; font-weight:600; }
          .dd-cap{ display:block; font-family:Inter,sans-serif; font-size:9px; text-transform:uppercase; letter-spacing:.16em;
            color:#8a8273; padding:8px 10px 3px; user-select:none; }
          .dd-cap:first-child{ padding-top:2px; }
          /* -- quick-jump search -- */
          [hidden]{ display:none !important; }
          .qj-open{ display:none; width:44px; height:44px; padding:0; border:0; border-radius:50%;
            background:none; color:#4a4439; cursor:pointer; align-items:center; justify-content:center; }
          .qj-open:hover, .qj-open:focus-visible{ color:#9a7322; background:#f1ece1; }
          .qj{ position:relative; }
          .qj-field{ display:flex; align-items:center; gap:7px; height:36px; width:200px; padding:0 6px 0 12px;
            border:1px solid #d8d2c6; border-radius:18px; background:#fff; color:#8a8273;
            transition:width .2s ease, border-color .15s; box-sizing:border-box; }
          .qj-field:focus-within{ width:280px; border-color:#9a7322; color:#9a7322; }
          .qj-field svg{ flex-shrink:0; }
          .qj-input{ flex:1; min-width:0; border:0; outline:0; background:transparent; padding:0;
            font:inherit; font-size:13px; color:#221f1a; -webkit-appearance:none; appearance:none; }
          .qj-input::placeholder{ color:#8a8273; }
          .qj-input::-webkit-search-cancel-button{ display:none; }
          .qj-kbd{ font:11px/16px Inter,sans-serif; min-width:16px; text-align:center; border:1px solid #d8d2c6;
            border-radius:4px; padding:0 3px; color:#8a8273; margin-right:4px; }
          .qj-field:focus-within .qj-kbd{ display:none; }
          .qj-close{ display:none; }
          .qj-panel{ position:fixed; z-index:70; box-sizing:border-box; width:min(460px, calc(100vw - 16px));
            max-height:min(72vh, 600px); overflow-y:auto; overscroll-behavior:contain;
            background:#fff; border:1px solid #d8d2c6; border-radius:10px; padding:6px;
            box-shadow:0 18px 48px -18px rgba(60,45,20,.5); font-family:Inter,system-ui,sans-serif; }
          .qj-status{ font-size:12px; color:#6b6457; padding:6px 8px; }
          .qj-status:empty{ display:none; }
          .qj-try{ display:flex; flex-wrap:wrap; gap:6px; padding:2px 6px 8px; }
          .qj-try button{ min-height:36px; padding:0 12px; border:1px solid #d8d2c6; border-radius:18px; background:#fbf9f3;
            color:#4a4439; font:inherit; font-size:13px; cursor:pointer; }
          .qj-try button:hover{ border-color:#9a7322; color:#9a7322; }
          .qj-row{ display:flex; align-items:center; gap:11px; min-height:48px; padding:3px 8px; border-radius:8px;
            color:#221f1a; text-decoration:none; }
          .qj-row[aria-selected="true"]{ background:#f1ece1; }
          .qj-thumb{ flex:0 0 30px; width:30px; height:42px; display:flex; align-items:center; justify-content:center;
            background:#f6f2e9; border-radius:3px; color:#9a7322; overflow:hidden; }
          .qj-thumb img{ width:100%; height:100%; object-fit:contain; display:block; }
          .qj-text{ min-width:0; display:flex; flex-direction:column; gap:1px; }
          .qj-t{ font-size:14px; line-height:1.3; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .qj-s{ font-size:12px; line-height:1.3; color:#6b6457; display:flex; align-items:center; gap:5px; min-width:0; }
          .qj-s span{ white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .qj-s svg{ flex-shrink:0; color:#9a7322; }
          @media (max-width:680px){
            .qj-open{ display:inline-flex; }
            .qj{ display:none; }
            .qj.sheet{ display:flex; flex-direction:column; position:fixed; inset:0; z-index:100;
              background:#fbf9f3; padding:10px 16px 0; box-sizing:border-box; }
            .qj.sheet .qj-field, .qj.sheet .qj-field:focus-within{ width:100%; height:48px; border-radius:24px; padding:0 2px 0 14px; }
            .qj.sheet .qj-input{ font-size:16px; }
            .qj.sheet .qj-kbd{ display:none; }
            .qj.sheet .qj-close{ display:inline-flex; flex-shrink:0; width:44px; height:44px; padding:0; border:0; border-radius:50%;
              background:none; color:#4a4439; align-items:center; justify-content:center; cursor:pointer; }
            .qj.sheet .qj-panel{ position:static; flex:1; width:auto; max-height:none; border:0; border-radius:0;
              box-shadow:none; background:transparent; padding:8px 0 24px; }
            .qj.sheet .qj-row{ min-height:52px; }
          }
          @media (max-width:680px){
            .brand .sub{ display:none; }
            .tab{ padding:5px 8px; font-size:12px; }
            .cap{ display:none; } .sep{ display:none; }
          }
        </style>
        <div class="bar">
          <span class="brand">
            <a class="brand-logo" href="https://recursive.eco" target="_blank" rel="noopener" title="Part of recursive.eco — the parent project" aria-label="recursive.eco — the parent project">
              <span style="display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;background:#fff;border-radius:50%;flex-shrink:0"><img src="${PFX}public/spiral-purple.svg" width="30" height="30" alt="" aria-hidden="true" style="display:block"></span>
            </a>
            <a class="brand-name" href="${PFX}index.html" title="The Recursive Tarot — home">
              <span class="name">The <span class="gold">Recursive Tarot</span></span>
            </a>
          </span>
          <span class="spacer"></span>
          <button class="qj-open" type="button" aria-label="Search cards, decks and chapters" title="Search">${QJ_SVG(QJ_ICON.search, 22)}</button>
          <div class="qj" role="search">
            <div class="qj-field">
              ${QJ_SVG(QJ_ICON.search, 16)}
              <input class="qj-input" type="search" enterkeyhint="go" autocomplete="off" autocapitalize="off" spellcheck="false"
                     placeholder="Card, deck, chapter" aria-label="Find a card, deck or chapter"
                     role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="qj-list">
              <kbd class="qj-kbd" aria-hidden="true">/</kbd>
              <button class="qj-close" type="button" aria-label="Close search">${QJ_SVG(QJ_ICON.close, 20)}</button>
            </div>
            <div class="qj-panel" hidden>
              <div class="qj-status" aria-live="polite"></div>
              <div class="qj-list" id="qj-list" role="listbox" aria-label="Search results"></div>
            </div>
          </div>
          <nav aria-label="Site sections">
            <span class="dd">
              <a class="tab dd-btn${active === 'home' ? ' active' : ''}" href="${PFX}index.html" aria-haspopup="true" aria-expanded="false" aria-label="Home menu">Home</a>
              <span class="dd-menu">
                ${HOME_MENU.map(([href, label]) => `<a href="${href}">${label}</a>`).join('')}
              </span>
            </span>
            <span class="dd">
              <a class="tab dd-btn${viewActive ? ' active' : ''}" role="button" tabindex="0" aria-haspopup="true" aria-expanded="false" aria-label="Views menu">Views</a>
              <span class="dd-menu">
                <span class="dd-cap">By card</span>
                ${CARD_VIEWS.map(menuItem).join('')}
                <span class="dd-cap">Across the collection</span>
                ${GRAMMAR_VIEWS.map(menuItem).join('')}
              </span>
            </span>
            <span class="dd">
              <a class="tab t-course dd-btn${active === 'course' ? ' active' : ''}" role="button" tabindex="0" aria-haspopup="true" aria-expanded="false" aria-label="Courses menu">Courses</a>
              <span class="dd-menu">
                ${COURSE_GROUPS.map(([cap, items]) => `<span class="dd-cap">${cap}</span>` + items.map(([id, label]) => `<a href="${PFX}pages/course-viewer.html?course=${id}">${label}</a>`).join('')).join('')}
                <a href="${PFX}pages/courses.html" style="border-top:1px solid #d8d2c6;margin-top:4px;padding-top:9px">All courses (gallery) →</a>
                <a href="${PFX}pages/sources.html">The sources — people &amp; books →</a>
              </span>
            </span>
            <span class="dd">
              <a class="tab t-caster dd-btn${active === 'play' ? ' active' : ''}" href="${PFX}pages/play.html" aria-haspopup="true" aria-expanded="false" aria-label="Play menu">Play</a>
              <span class="dd-menu">
                ${PLAY_MENU.map(([href, label, ext]) => `<a href="${href}"${ext ? ' target="_blank" rel="noopener"' : ''}>${label}</a>`).join('')}
              </span>
            </span>
            ${TOOLS.map(tab).join('')}
            <recursive-auth></recursive-auth>
          </nav>
        </div>`;

      // Dropdowns: keyboard + ARIA on top of the hover/focus-within CSS. Panels are
      // right-anchored by default (.dd-menu right:0), which reads fine when the trigger
      // sits near the right of the nav — but a left-side trigger (Home, Views) has less
      // room to its left than the panel needs, at tablet widths as much as on phones.
      // positionMenu() measures the real trigger + panel on every open and clamps
      // left/top so the panel always stays fully on-screen, at any width.
      const DD_EDGE = 8; // min gap kept between a panel and the viewport edge
      const positionMenu = dd => {
        const menu = dd.querySelector('.dd-menu');
        if (!menu) return;
        const ddRect = dd.getBoundingClientRect();
        const menuRect = menu.getBoundingClientRect();
        const vw = window.innerWidth, vh = window.innerHeight;
        // Natural position mirrors the CSS default (panel's right edge flush with the
        // trigger's right edge), then clamp so neither edge crosses the viewport.
        let left = ddRect.right - menuRect.width;
        left = Math.max(DD_EDGE, Math.min(left, vw - menuRect.width - DD_EDGE));
        menu.style.left = (left - ddRect.left) + 'px';
        menu.style.right = 'auto';
        // Vertical: cap height + let the panel scroll internally rather than running
        // off the bottom of short viewports (e.g. a phone in landscape).
        const top = ddRect.bottom + 8;
        menu.style.maxHeight = Math.max(120, vh - top - DD_EDGE) + 'px';
      };
      root.querySelectorAll('.dd').forEach(dd => {
        const btn = dd.querySelector('.dd-btn');
        const set = open => btn && btn.setAttribute('aria-expanded', open ? 'true' : 'false');
        const closeAll = except => root.querySelectorAll('.dd.open').forEach(o => {
          if (o === except) return;
          o.classList.remove('open'); const b = o.querySelector('.dd-btn'); if (b) b.setAttribute('aria-expanded', 'false');
        });
        let closeTimer = null;
        const open = () => { clearTimeout(closeTimer); closeAll(dd); dd.classList.add('open'); set(true); positionMenu(dd); };
        const close = () => { clearTimeout(closeTimer); dd.classList.remove('open'); set(false); };
        // Desktop hover: JS-managed with a grace period on close. Pure CSS :hover
        // closed the panel the instant the cursor crossed the gap under the trigger
        // (a dead zone no bridge can cover once the panel scrolls) — and a delay
        // also survives the horizontal shift positionMenu applies near screen edges.
        dd.addEventListener('mouseenter', () => { if (window.matchMedia('(hover: hover)').matches) open(); });
        dd.addEventListener('mouseleave', () => {
          if (!window.matchMedia('(hover: hover)').matches) return;
          clearTimeout(closeTimer); closeTimer = setTimeout(close, 260);
        });
        dd.addEventListener('focusin', () => { set(true); positionMenu(dd); });
        dd.addEventListener('focusout', () => { if (!dd.matches(':focus-within')) set(false); });
        dd.addEventListener('keydown', e => {
          if (e.key === 'Escape') { close(); btn && btn.focus(); }
          // Enter/Space opens the menu when the trigger has no own link to follow
          if ((e.key === 'Enter' || e.key === ' ') && e.target === btn && !btn.getAttribute('href')) {
            const first = dd.querySelector('.dd-menu a'); if (first) { e.preventDefault(); set(true); positionMenu(dd); first.focus(); }
          }
        });
        // Touch / no-hover devices: tap the tab to toggle its menu (hover never fires).
        // Desktop (hover-capable) keeps hover-to-open + click-to-follow-link untouched.
        btn.addEventListener('click', e => {
          if (window.matchMedia('(hover: hover)').matches) return;
          e.preventDefault();
          const willOpen = !dd.classList.contains('open');
          closeAll(null);
          if (willOpen) open(); else close();
        });
      });

      // Close any open menu when tapping outside the header (touch).
      document.addEventListener('click', e => {
        if (!e.composedPath().includes(this)) {
          root.querySelectorAll('.dd.open').forEach(o => { o.classList.remove('open'); const b = o.querySelector('.dd-btn'); if (b) b.setAttribute('aria-expanded', 'false'); });
        }
      });

      // Reposition any currently-open menu on resize/orientation-change (e.g. rotating
      // a tablet with a dropdown open) — a fixed breakpoint can't react to this either.
      window.addEventListener('resize', () => {
        root.querySelectorAll('.dd').forEach(dd => {
          const menu = dd.querySelector('.dd-menu');
          if (menu && getComputedStyle(menu).display !== 'none') positionMenu(dd);
        });
      });

      this.wireQuickJump(root);

      // Auto-hide on scroll down, reveal on scroll up — but never while the nav has keyboard focus.
      let lastY = window.scrollY || 0, host = this;
      window.addEventListener('scroll', () => {
        const y = window.scrollY || 0;
        const hide = y > 90 && y > lastY + 4 && !host.matches(':focus-within');
        // '' rather than translateY(0) when shown: any transform on the host makes it the
        // containing block for position:fixed, which would trap the search panel and sheet.
        host.style.transform = hide ? 'translateY(-100%)' : '';
        lastY = y;
      }, { passive: true });
    }
  }
  // Quick-jump search box. Desktop: the field sits in the bar and a results panel drops
  // under it as you type. Phone (<=680px): a search icon opens a full-screen sheet.
  // Arrow keys move, Enter opens, Escape clears then closes; "/" or Ctrl/Cmd+K focuses it.
  SiteHeader.prototype.wireQuickJump = function (root) {
    const host = this;
    const qj = root.querySelector('.qj'), field = root.querySelector('.qj-field');
    const input = root.querySelector('.qj-input'), panel = root.querySelector('.qj-panel');
    const list = root.querySelector('.qj-list'), status = root.querySelector('.qj-status');
    const openBtn = root.querySelector('.qj-open'), closeBtn = root.querySelector('.qj-close');
    let index = null, loading = null, results = [], active = -1, lastQ = null;
    const isSheet = () => qj.classList.contains('sheet');

    const engine = () => {
      if (index) return Promise.resolve(index);
      if (!loading) {
        loading = new Promise((res, rej) => {
          if (window.RTQuickJump) return res();
          const s = document.createElement('script');
          s.src = PFX + 'quick-jump.js?v=1';
          s.onload = res; s.onerror = () => rej(new Error('quick-jump.js did not load'));
          document.head.appendChild(s);
        }).then(() => window.RTQuickJump.load(PFX)).then(i => { index = i; render(); return i; })
          .catch(err => { loading = null; status.textContent = 'Search is unavailable right now.'; throw err; });
      }
      return loading;
    };

    const place = () => {
      if (isSheet()) { panel.style.top = panel.style.left = ''; return; }
      const r = field.getBoundingClientRect(), w = panel.offsetWidth || 460;
      panel.style.top = Math.round(r.bottom + 6) + 'px';
      panel.style.left = Math.round(Math.max(8, Math.min(r.right - w, window.innerWidth - w - 8))) + 'px';
    };
    const showPanel = on => {
      panel.hidden = !on;
      input.setAttribute('aria-expanded', on && results.length ? 'true' : 'false');
      if (on) place();
    };
    const setActive = i => {
      const rows = list.querySelectorAll('.qj-row');
      if (!rows.length) { active = -1; input.removeAttribute('aria-activedescendant'); return; }
      active = (i + rows.length) % rows.length;
      rows.forEach((r, n) => r.setAttribute('aria-selected', n === active ? 'true' : 'false'));
      input.setAttribute('aria-activedescendant', rows[active].id);
      rows[active].scrollIntoView({ block: 'nearest' });
    };
    const thumb = r => r.img && (r.kind === 'c' || r.kind === 'd')
      ? `<img src="${qjEsc(r.img)}" alt="" loading="lazy" decoding="async">`
      : QJ_SVG(QJ_ICON[r.kind] || QJ_ICON.c, 20);
    const render = () => {
      const q = input.value.trim();
      if (!q) {
        results = []; list.innerHTML = ''; active = -1;
        status.innerHTML = `<div class="qj-try">${QJ_TRY.map(t => `<button type="button" data-q="${qjEsc(t)}">${qjEsc(t)}</button>`).join('')}</div>`;
        showPanel(isSheet() || document.activeElement === host && root.activeElement === input);
        return;
      }
      if (!index) { status.textContent = 'Loading…'; list.innerHTML = ''; showPanel(true); engine(); return; }
      if (q === lastQ && list.childElementCount) { showPanel(true); return; }
      lastQ = q;
      results = window.RTQuickJump.search(index, q, 60);
      status.textContent = results.length ? '' : 'Nothing found. Try a card name, a numeral (XI) or a deck.';
      list.innerHTML = results.map((r, n) => `
        <a class="qj-row" id="qj-o${n}" role="option" aria-selected="false" href="${qjEsc(r.href)}">
          <span class="qj-thumb">${thumb(r)}</span>
          <span class="qj-text"><span class="qj-t">${qjEsc(r.title)}</span>
            <span class="qj-s">${QJ_SVG(QJ_ICON[r.kind] || QJ_ICON.c, 13)}<span>${qjEsc(r.sub)}</span></span></span>
        </a>`).join('');
      showPanel(true);
      setActive(0);
      list.scrollTop = 0;
    };

    const openSheet = () => {
      qj.classList.add('sheet');
      host.style.zIndex = '2147483001';           // above the page's overlays (the assistant star sits at 2147483000)
      document.documentElement.style.overflow = 'hidden';
      input.focus();
      engine().catch(() => {});
      render();
    };
    const close = () => {
      showPanel(false);
      if (isSheet()) {
        qj.classList.remove('sheet');
        host.style.zIndex = '';
        document.documentElement.style.overflow = '';
        openBtn.focus();
      }
    };

    openBtn.addEventListener('click', openSheet);
    closeBtn.addEventListener('click', () => { input.value = ''; lastQ = null; close(); });
    input.addEventListener('focus', () => { engine().catch(() => {}); render(); });
    input.addEventListener('input', render);
    input.addEventListener('keydown', e => {
      if (e.key === 'ArrowDown') { e.preventDefault(); if (panel.hidden) render(); else setActive(active + 1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); setActive(active - 1); }
      else if (e.key === 'Enter') {
        const rows = list.querySelectorAll('.qj-row');
        const row = rows[active] || rows[0];
        if (!row) return;
        e.preventDefault();
        if (e.ctrlKey || e.metaKey) window.open(row.href, '_blank', 'noopener');
        else location.href = row.href;
      } else if (e.key === 'Escape') {
        e.preventDefault(); e.stopPropagation();
        if (input.value) { input.value = ''; lastQ = null; render(); }
        else { close(); if (!isSheet()) input.blur(); }
      }
    });
    // Keep focus in the box while a result or a "try" chip is clicked (the click still fires).
    panel.addEventListener('mousedown', e => e.preventDefault());
    panel.addEventListener('mousemove', e => {
      const row = e.target.closest && e.target.closest('.qj-row');
      if (row) { const n = [...list.children].indexOf(row); if (n !== active) setActive(n); }
    });
    status.addEventListener('click', e => {
      const b = e.target.closest && e.target.closest('button[data-q]');
      if (b) { input.value = b.dataset.q; input.focus(); render(); }
    });
    qj.addEventListener('focusout', e => {
      if (isSheet()) return;                      // the phone keyboard's "done" must not close the sheet
      if (!e.relatedTarget || !qj.contains(e.relatedTarget)) showPanel(false);
    });
    window.addEventListener('resize', () => {
      if (isSheet() && window.innerWidth > 680) close();
      if (!panel.hidden) place();
    });
    window.addEventListener('scroll', () => { if (!panel.hidden) place(); }, { passive: true });
    document.addEventListener('keydown', e => {
      const t = e.composedPath()[0] || e.target;
      const typing = t && (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName || ''));
      const k = (e.key === '/' && !typing && !e.ctrlKey && !e.metaKey && !e.altKey) ||
                ((e.ctrlKey || e.metaKey) && (e.key === 'k' || e.key === 'K'));
      if (!k || host.style.display === 'none') return;
      e.preventDefault();
      if (getComputedStyle(openBtn).display !== 'none') openSheet(); else input.focus();
    });
  };

  customElements.define('site-header', SiteHeader);
})();
