# -*- coding: utf-8 -*-
"""narration_script.py — turn a course MDX into a beat-by-beat SCREENCAST script:
for each section, the on-screen action (commands to run/show), the voice-over line, and a
target duration. This is the input a recorder (you, or Claude Code performing the steps live
while asciinema/OBS captures the terminal) follows; assemble_performance.py then cuts the
recording into a sequence grammar.

  python3 pipeline/narration_script.py pipeline/sample/vibe-coding-101.mdx \
          productions/vibe-coding-101/screencast-script.md
"""
import os, re, sys

WPM = 150  # narration words-per-minute, for duration estimates

def strip_frontmatter(t):
    m = re.match(r'^---\s*\n.*?\n---\s*\n', t, re.S)
    return t[m.end():] if m else t

def sentences(prose):
    prose = re.sub(r'`([^`]+)`', r'\1', prose)               # inline code → plain
    prose = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', prose)   # links → text
    prose = re.sub(r'[*_#>|]', '', prose)
    prose = re.sub(r'\s+', ' ', prose).strip()
    return [s.strip() for s in re.split(r'(?<=[.!?])\s+', prose) if len(s.strip()) > 3]

def parse(md):
    """Split into scenes at H2/H3; collect prose + fenced code blocks per scene."""
    md = strip_frontmatter(md)
    scenes, cur = [], {"title": "Intro", "prose": [], "code": []}
    in_code, buf = False, []
    for line in md.splitlines():
        if line.startswith('```'):
            if in_code: cur["code"].append("\n".join(buf)); buf = []
            in_code = not in_code; continue
        if in_code: buf.append(line); continue
        h = re.match(r'^(#{2,3})\s+(.*)', line)
        if h:
            if cur["prose"] or cur["code"]: scenes.append(cur)
            cur = {"title": h.group(2).strip(), "prose": [], "code": []}
        elif line.strip():
            cur["prose"].append(line)
    if cur["prose"] or cur["code"]: scenes.append(cur)
    return scenes

def script(md, title="Course"):
    out = [f"# Screencast script — {title}", "",
           "*Generated by pipeline/narration_script.py. Voice-over lines are read aloud; "
           "On-screen = what to do/show in the terminal (Claude Code can perform these live "
           "while the screen records).*", ""]
    total = 0.0
    for n, sc in enumerate(parse(md), 1):
        narration = " ".join(sentences(" ".join(sc["prose"]))[:4])  # first ~4 sentences = the beat
        dur = max(5, round(len(narration.split()) / WPM * 60))
        total += dur + (4 if sc["code"] else 0)
        out += [f"## Scene {n} — {sc['title']}  ·  ~{dur}s", "",
                f"**🎙 Voice-over:** {narration or '(silent beat — show the screen)'}", ""]
        if sc["code"]:
            out.append("**⌨ On-screen (run/show):**")
            for c in sc["code"]:
                out += ["```", c.strip(), "```"]
            out.append("")
    out += ["---", f"*Estimated runtime: ~{total/60:.1f} min across the scenes above. "
            "Replace estimates with real clip boundaries after recording.*"]
    return "\n".join(out)

if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "pipeline/sample/vibe-coding-101.mdx"
    dst = sys.argv[2] if len(sys.argv) > 2 else "productions/vibe-coding-101/screencast-script.md"
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    md = open(os.path.join(root, src), encoding="utf-8").read()
    title = (re.search(r'title:\s*"([^"]+)"', md) or [None, "Course"])[1]
    os.makedirs(os.path.dirname(os.path.join(root, dst)), exist_ok=True)
    open(os.path.join(root, dst), "w", encoding="utf-8").write(script(md, title))
    print(f"wrote {dst}")
